spring:
    freemarker:
        settings:
            locale: pt_BR
    jackson:
        deserialization:
            fail-on-ignored-properties: true
            fail-on-unknown-properties: true
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                '[format_sql]': true
        show-sql: true
    web:
        resources:
            add-mappings: false
    datasource:
        password: ranger19
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        url: jdbc:mysql://localhost:3308/dbsocial?createDatabaseIfNotExist=true&serverTimezone=UTC
    output:
        ansi:
            enabled: NEVER
    flyway:
        locations: classpath:db/migration,classpath:db/testdata
    mvc:
        throw-exception-if-no-handler-found: true
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
portalsocial:
    storage:
        local:
            diretorio-fotos: /Users/Acer/OneDrive/Geral
        s3:
            bucket: algafoods-glr
            regiao: us-east-1
            diretorio-fotos: catalogo
            id-chave-acesso: ${AWS_S3_KEY}
            chave-acesso-secreta: ${AWS_S3_SECRET_KEY}
        tipo: local
logging:
    level:
        org:
            springframework:
                web: DEBUG
server:
    error:
        include-message: always
        include-stacktrace: always
